<?php
	$DESGNER_CONFIG_SWITCH	 = $this->getConfig('enabled');
	if($DESGNER_CONFIG_SWITCH):
	$designername   		 = base64url_decode($_GET['designername']);
	//designername 等于空
	if(empty($designername)):
	$DESGNER_LIST_CONNECTION = Mage::getModel('core/resource')->getConnection('core_read');
	$GET_DESGNER_LIST_DB	 = $DESGNER_LIST_CONNECTION->select()->from('magentothem_designer',"title");
	$DESGNER_LIST_ALL		 = $DESGNER_LIST_CONNECTION->fetchAll($GET_DESGNER_LIST_DB);
	
	foreach($DESGNER_LIST_ALL as $key=>$value):
		$DESGNER_LIST_TITLE[]=$value['title'];
	endforeach;
	$LASTCHAR = '';
	
	sort($DESGNER_LIST_TITLE, SORT_STRING | SORT_FLAG_CASE);
	
	foreach($DESGNER_LIST_TITLE as $DESGNER_KEY):
		
	  $DESGNER_FIRST_CHAR = $DESGNER_KEY[0]; //first char
	  
		if ($DESGNER_FIRST_CHAR !== $LASTCHAR):
			
			//if ($LASTCHAR !== '')
?>

<section class="mainWrap2 clearfix">
    <div class="designerlist">
		<dl>
            <dt>
				<span>
				
					<?php
					
						ECHO strtoupper($DESGNER_FIRST_CHAR);
						
						$LASTCHAR = $DESGNER_FIRST_CHAR;
						
					?>
					
				</span>
			</dt>
			
		<?php endif; ?>
		
                <dd>
					<a href="?designername=<?php ECHO base64url_encode($DESGNER_KEY);?>" title="<?php ECHO $DESGNER_KEY;?>">
						<?php ECHO strtoupper($DESGNER_KEY);?>
					</a>
				</dd>
				
 <?php endforeach; ?>
 
		</dl>
	</div>	
</section>
<?php //designername 不等于空 else?>
<?php else: ?>





<?php
$visibility = array(
    Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH, 
    Mage_Catalog_Model_Product_Visibility::VISIBILITY_IN_CATALOG
);
$_productCollection = Mage::getModel('catalog/product')
    ->getCollection()
//$_productCollection = Mage::getResourceModel('reports/product_collection')
	->addAttributeToSelect('*')
    //->addOrderedQty()
	->addAttributeToFilter('newdesigner', array('like' => '%'.$designername.'%'));
    //->addAttributeToFilter('visibility', $visibility)
    //->setOrder('ordered_qty', 'desc');
$_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-products">
    <?php echo $this->getToolbarHtml() ?>
    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = 3 ?>
    <?php $i=0; foreach ($_productCollection as $_product): ?>
    <?php if ($i++%$_columnCount==0): ?>
    <ul class="products-grid row">
		<?php endif ?> 
		<li class="col-sm-4 col-md-4 col-xs-12 item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
			<div class="item-inner">
				<div class="ma-box-content">
					<?php
					$newFromDate = $_product->getNewsFromDate();
					$newToDate = $_product->getNewsToDate();                 
					$now = date("Y-m-d H:m:S");
					// Get the Special Price
					$specialprice = $_product->getSpecialPrice(); 
					// Get the Special Price FROM date
					$specialPriceFromDate = $_product->getSpecialFromDate();
					// Get the Special Price TO date
					$specialPriceToDate = $_product->getSpecialToDate();
					// Get Current date
					if ($specialprice&&($specialPriceFromDate <= $now && $specialPriceToDate >= $now)&& Mage::getStoreConfig('themeoptions/themeoptions_config/sale_label')){
						echo '<div class="label-pro-sale"><span>sale</span></div>';
					}else{
						if($newFromDate <= $now && $newToDate >= $now && Mage::getStoreConfig('themeoptions/themeoptions_config/new_label') ) {
						   echo '<div class="label-pro-new"><span>new</span></div>';
						}
					}
					?>
					<div class="products">
						 <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
						  <span class="product-image">
						   <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(540,728); ?>" width="540" height="728" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
						  </span>
						  <span class="product-image image-rotator">
						   <?php 
						   $product = Mage::getModel('catalog/product')->load($_product->getId());
						   if ($product->getRotatorImage() && $product->getRotatorImage() !='no_selection') {
							//$imageTooltipResize = $this->getResizedUrl($imagetTooltip,600,400);
							$image = Mage::helper('catalog/image')->init($product, 'rotator_image')->resize(540, 728);
						   } else {
							$image = Mage::helper('catalog/image')->init($_product, 'small_image')->resize(540, 728);
						   }
						   ?>
						   <img src="<?php echo $image ?>" width="540" height="728" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
						   </span>   
						</a>
						
						<div class="actions clearfix">
							<?php if($_product->isSaleable()): ?>
								<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><i class="fa fa-shopping-cart"></i><?php //echo $this->__('Add to Cart') ?></span></button>
								<?php else: ?>
									<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
							<?php endif; ?>
							<ul class="add-to-links">
								<?php if ($this->helper('wishlist')->isAllow()) : ?>
									<li class="last"><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" title="<?php echo $this->__('Add to Wishlist') ?>" class="link-wishlist fa fa-heart"><?php //echo $this->__('Add to Wishlist') ?></a></li>
								<?php endif; ?>
								<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
									<li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" title="<?php echo $this->__('Add to Compare') ?>" class="link-compare fa fa-retweet"><?php //echo $this->__('Add to Compare') ?></a></li>
								<?php endif; ?>
							</ul>
						</div>
						
					</div>
					<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
					<?php if($_product->getRatingSummary()): ?>
						<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
					<?php endif; ?>
					<?php echo $this->getPriceHtml($_product, true) ?>
					
				</div>
			</div>
		</li>
		<?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
    </ul>
		     <?php endif ?>
			<?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>
</div>
<?php endif; ?>
<?php //designername 不等于空  结束?>
<?php endif; ?>

<?php //这个是控制页面开关的判断。?>
<?php else: echo $this->__('Designer Page Not Open'); endif; ?>



<?php
	function base64url_encode($data) { return rtrim(strtr(base64_encode($data), '+/', '-_'), '='); } 
	function base64url_decode($data) { return base64_decode(str_pad(strtr($data, '-_', '+/'), strlen($data) % 4, '=', STR_PAD_RIGHT)); } 
?>
